# Generated by Django 4.2.23 on 2025-07-21 08:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenoms', models.CharField(help_text="Entrez le prénom de l'auteur", max_length=100)),
                ('nom', models.CharField(help_text="Entrez le nom de l'auteur", max_length=100)),
                ('date_naissance', models.DateField(blank=True, help_text="Entrez la date de naissance de l'auteur", null=True)),
                ('date_de_deces', models.DateField(blank=True, help_text="Entrez la date de décès de l'auteur", null=True, verbose_name='Décédé')),
            ],
            options={
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Entrez le nom du genre d'un livre ex: Littérrature, Science-fiction, etc.", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Entrez le titre du livre', max_length=200)),
                ('resume', models.TextField(help_text='Entrez le résumé du livre', max_length=1000)),
                ('isbn', models.CharField(help_text="Entrez l'ISBN du livre", max_length=13, unique=True, verbose_name='ISBN')),
                ('auteur', models.ForeignKey(help_text="Entrez le nom de l'auteur du livre", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.auteur')),
                ('genre', models.ManyToManyField(help_text='Sélectionnez le genre du livre', to='catalogue.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text="Identifiant unique de l'exemplaire", primary_key=True, serialize=False)),
                ('date_retour', models.DateField(blank=True, help_text="Entrez la date de retour prévue de l'exemplaire", null=True)),
                ('numero_exemplaire', models.CharField(help_text="Entrez le numéro de l'exemplaire", max_length=20)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('e', 'Emprunté'), ('d', 'Disponible'), ('r', 'Réservé')], default='m', help_text='disponibilité Livre', max_length=1)),
                ('livre', models.ForeignKey(help_text='Sélectionnez le livre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.livre')),
            ],
            options={
                'ordering': ['date_retour'],
            },
        ),
    ]
