# Generated by Django 6.1 on 2026-08-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, help_text="Entrez l'email de l'étudiant", max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(blank=True, help_text="Entrez le prénom de l'étudiant", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='emprunteur',
            field=models.ForeignKey(blank=True, help_text='Étudiant ayant emprunté cet exemplaire', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.etudiant'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='date_de_deces',
            field=models.DateField(blank=True, help_text='Date de décès', null=True, verbose_name='Décédé'),
        ),
        migrations.AlterField(
            model_name='auteur',
            name='date_naissance',
            field=models.DateField(blank=True, help_text='Date de naissance', null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(blank=True, help_text="Entrez le nom de l'étudiant", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='titre',
            field=models.CharField(choices=[('M', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], help_text="Sélectionnez le titre de l'étudiant", max_length=10),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='date_retour',
            field=models.DateField(blank=True, help_text='Date de retour prévue', null=True),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(help_text='Livre correspondant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.livre'),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='numero_exemplaire',
            field=models.CharField(help_text="Numéro d'inventaire / Code-barres", max_length=20),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('e', 'Emprunté'), ('d', 'Disponible'), ('r', 'Réservé')], default='m', help_text='Disponibilité du livre', max_length=1),
        ),
        migrations.AlterField(
            model_name='genre',
            name='nom',
            field=models.CharField(help_text='Entrez le nom du genre (ex: Littérature, Science-fiction, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(help_text='Auteur du livre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.auteur'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='genre',
            field=models.ManyToManyField(help_text='Sélectionnez le ou les genres du livre', to='catalogue.genre'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(help_text='Code ISBN (13 caractères)', max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livre',
            name='resume',
            field=models.TextField(help_text='Résumé du livre', max_length=1000),
        ),
    ]
